### ISSUE TITLE
bug: `ignore in alfred` is not working as intended

### ISSUE THREAD

**Issue by wajeht** [alfredapp/ignore-in-alfred-workflow#1]
# Workflow version
- ignore in Alfred v2022.2

# Alfred version
- Alfred 5.0.5 [2096]

# macOS version
- Ventura 13.0.1

# Debug Output
```bash
[22:37:07.448] Logging Started...
[22:37:15.479] Ignore in Alfred[File Action] Processing complete
[22:37:15.480] Ignore in Alfred[File Action] Passing output '/Users/jaw/flutter' to Automation Task
[22:37:15.482] ERROR: Ignore in Alfred[Automation Task] Task not found 'com.alfredapp.automation.core/files-and-folders/path.tags.add'
```
# More Details
Hi, I am trying to exclude `flutter` sdk from my home directory. Somehow it is not being excluded. I have restarted my system multiple times. Removeed and Re-added the `ignore in alfred` workflow multiple times. I have also excluded the `flutter` folder in spotlight indexing multiple times. Am I missing anything here?

<img width="764" alt="Screenshot 2022-11-19 at 10 36 39 PM" src="https://user-images.githubusercontent.com/58354193/202881720-43f74e0c-7b1a-4ec8-b14c-4f21cd5af222.png">

<img width="1555" alt="Screenshot 2022-11-19 at 10 36 27 PM" src="https://user-images.githubusercontent.com/58354193/202881763-d3f01996-3132-41ab-b351-302ad1bcaa18.png">

<img width="827" alt="Screenshot 2022-11-19 at 10 46 38 PM" src="https://user-images.githubusercontent.com/58354193/202883295-f7572abf-92d2-46d1-8b71-6be3a0a65fe2.png">

**Comment by vitorgalvao** [comment]
The debug log explains it, you’re missing the Automation Task. Double-click the object in the canvas (it has red in it) and update from it.

The Spotlight privacy is a different method. For that not to work, there may be a problem with your index. But one thing at a time, do the above first.

**Comment by vitorgalvao** [comment]
The debug log explains it, you’re missing the Automation Task. Double-click the object in the canvas (it has red in it) and update from it.

The Spotlight privacy is a different method.

For folders directly under you home, go to Alfred Preferences → Features → Default Results and Reset the Search Scope to Applications and Home.
