### ISSUE TITLE
Ignore not working

### ISSUE THREAD

**Issue by sknud-create** [alfredapp/ignore-in-alfred-workflow#3]
### Workflow version

2023.1

### Alfred version

5.0.6

### macOS version

Ventura 13.2.1

### Debugger output

```alfred_debugger
Unsure
```

### More details

When going to ignore a file it does not work. Confirmed by going to reignore files, and it says nothing is tagged with ignore.

**Comment by vitorgalvao** [comment]
> Debugger output
>
> Unsure

Can’t debug without that. If you’re not sure how to open the debugger, [there is a help page](https://www.alfredapp.com/help/workflows/advanced/debugger/).

Where are your files located? If they’re directly under your home folder they won’t be ignored without [a tweak](https://github.com/alfredapp/ignore-in-alfred-workflow/issues/2#issuecomment-1370780243).

**Comment by vitorgalvao** [comment]
Closing for lack of reply.
