### ISSUE TITLE
Error regarding insufficient privileges

### ISSUE THREAD

**Issue by rccalma** [alfredapp/ignore-in-alfred-workflow#4]
Hi,

I am using "Ignore in Alfred." It seems to work for some apps (for me, that case is Spotify), and not for others (ex. Word). I got the following error:
[11:04:13.113] ERROR: Ignore in Alfred[Automation Task] Task Error: Swift/ErrorType.swift:200: Fatal error: Error raised at top level: Error Domain=NSOSStatusErrorDomain Code=-5000 "afpAccessDenied: Insufficient access privileges for operation " UserInfo={NSURLKeysOfUnsetValuesKey=(
    NSURLTagNamesKey
)}

MACOS: 13.2.1 (22D68)
Alfred: 5.0.6 [2110]
Ignore in Alfred: v2023.1

Thank you for your help, and thank you for making such an amazing app!

**Comment by vitorgalvao** [comment]
Looks like Word is installed with higher permissions. What happens if you right-click → Get Info then add an `alfred:ignore` tag manually? Do you get a dialog? Does the operation work?

**Comment by rccalma** [comment]
That actually worked, thanks!

I don't understand how this happened: Is this behavior (of installing an application with 'higher permissions') something that is defaulted by the application (so in this case, Microsoft)?

**Comment by vitorgalvao** [comment]
It depends. Try installing an app from a downloaded DMG and one from the Mac App Store. Then delete them. You’ll see that the former will be deleted without a fuss, but for the latter Finder will ask you for elevated permissions.

This concept of permissions [goes way back](https://en.wikipedia.org/wiki/File-system_permissions) and allows for granularity of who can access what. It’s not something you typically have to worry about as a user, in this era of every one having a personal computing device, but it’s still useful for security reasons and the like.

**Comment by luckman212** [comment]
@vitorgalvao I hit this issue too (not using your workflow, but just on my own experimentation).

According to what I could find from looking at [the source](https://github.com/alfredapp/automation-tasks/blob/main/Tasks/com.alfredapp.automation.core/files-and-folders/path.tags.add/alfredtask.json), the AT uses the `tag` binary to do its work. I know it might not be the nicest solution, but I figured out that with a small stub file added to `/etc/sudoers.d/` the script could call `tag` with `sudo` fairly safely (sha256 hash verification + path matching) without prompting the user for a password. This should work around this issue.

I figure maybe a future version of the Tag automations UI could add an additional checkbox:
- [x] Run as root

**Instructions:**

1. execute the following command:

```
sudo visudo /etc/sudoers.d/alfred_tag
```

2. Paste in the contents below:
```
Cmnd_Alias ALFRED_TAG = sha256:GKj8Tw3KQCC6xnR/OvWOZaVCTtFZFEoJ25giNte2Vkc= /Users/*/Library/Application\ Support/Alfred/Automation/Tasks/com.alfredapp.automation.core/files-and-folders/.common/tag

%admin ALL=(ALL) NOPASSWD: ALFRED_TAG
```
3. save and exit.
4. run `sudo -k` to uncache the root password.
5. Now, you should be able to call this without any password prompt:
```shell
sudo "$HOME/Library/Application Support/Alfred/Automation/Tasks/com.alfredapp.automation.core/files-and-folders/.common/tag
```

If the hash value of `tag` changes in the future, here is the command to generate a new base64-encoded hash:

```
openssl dgst -binary -sha256 /path/to/tag | openssl base64
```

**Comment by vitorgalvao** [comment]
While I have total trust and control over the invoked `tag` binary (I wrote it), I consider editing the sudoers file to be [too complicated and dangerous to recommend to users](https://github.com/alfredapp/low-power-mode-workflow/issues/4#issuecomment-1407226793). It’s one of those cases where most people should never do it.

In that same vein, I discourage running things as root unless absolutely necessary so wouldn’t add it as a checkbox.

At the most I’d detect the situation then ask macOS for elevated permissions *for that case only*, but I’m wary of doing it in this case. Ignoring apps is quite a rare situation and even then not every app has the elevated permissions, only specific cases. With all of that together, having to do it manually in those cases seems the safest approach with minimal disruption.

**Comment by luckman212** [comment]
Got it. Yeah sudoers is pretty cumbersome. It took me ~2h just to arrive at a working solution in its cryptic [EBNF](https://www.sudo.ws/docs/man/1.8.15/sudoers.man/#Quick_guide_to_EBNF) (Extended Backus-Naur Form) language.

In case it saves some future person any time, the documented placeholders `%{user}` and `%u` do not seem to work in the path specification. That's why I ended up using `/Users/*/...`
