### ISSUE TITLE
Error Domain=NSOSStatusErrorDomain Code=-5000

### ISSUE THREAD

**Issue by ishigo974** [alfredapp/ignore-in-alfred-workflow#6]
### Workflow version

2023.2

### Alfred version

5.1.1

### macOS version

13.4

### Debugger output

```alfred_debugger
[11:05:38.687] Logging Started...
[11:05:41.231] Ignore in Alfred[File Filter] Processing complete
[11:05:41.232] Ignore in Alfred[File Filter] Passing output '/System/Applications/FindMy.app' to Automation Task
[11:05:41.233] Ignore in Alfred[Automation Task] Running task 'Add Tags' with arguments (
    "/System/Applications/FindMy.app"
)
[11:05:41.252] ERROR: Ignore in Alfred[Automation Task] Task Error: Swift/ErrorType.swift:200: Fatal error: Error raised at top level: Error Domain=NSOSStatusErrorDomain Code=-5000 "afpAccessDenied: Insufficient access privileges for operation " UserInfo={NSURLKeysOfUnsetValuesKey=(
    NSURLTagNamesKey
)}
```

### More details

Hello,

I'd like to ignore an app (Find My), but it seems like the ignore is not working because of permission issue. Is there a way to force it to be allowed or is it just not possible?
I tried a few things (adding permissions to Alfred in Privacy settings like "Full disk access" or "Accessibility"), didn't find any solution.
Could you help me about this?

Thank you very much

**Comment by vitorgalvao** [comment]
For apps with elevated permissions, [add the tag manually](https://github.com/alfredapp/ignore-in-alfred-workflow/issues/4#issuecomment-1460649745) and if it’s possible, Finder will ask you to authenticate. Find My should be under System Integrity Protection so it might not be possible at all without disabling it, *which is not recommended*.

**Comment by ishigo974** [comment]
Thanks for your quick answer. Seems not possible indeed.

**Comment by vitorgalvao** [comment]
Just remembered something else which should work. Go to System Settings → Siri & Spotlight → Spotlight Privacy… (way down at the bottom) and add it there. Then type `reload` in Alfred and press <kbd>↩&#xFE0E;</kbd>. That should get you sorted.

**Comment by ishigo974** [comment]
I think this allows to select a folder but not an app. Or system apps are blocked, because they are all greyed out, sadly.

<img width="668" alt="image" src="https://github.com/alfredapp/ignore-in-alfred-workflow/assets/6830504/6a01321c-2b39-451f-a5bc-18f938c4facd">

**Comment by vitorgalvao** [comment]
Don’t do it via the <kbd>+</kbd>, drag and drop the app directly on the area.

**Comment by ishigo974** [comment]
Genius!
Thank you so much, it works perfectly.

Thank you also for looking for multiple solutions ❤️
