### ISSUE TITLE
Ignore a specific application.

### ISSUE THREAD

**Issue by LittleNewton** [alfredapp/ignore-in-alfred-workflow#9]
### Feature details

Hi there,

ignore-in-alfred-workflow is such a wonderful and pretty useful one which helped me a lot. I just wonder if there a method to ignore a specific **application**. Such as `ChatGPT.app`, `Google Chrome.app` to be ignored.

**Comment by vitorgalvao** [comment]
Thank you for the kind words.

Alfred keeps a separate cache for applications, for speed. After ignoring (or unignoring) an app with the workflow, you have to Alfred Preferences → Advanced → Clear Application Cache.

Note ignoring will not work on apps (or other files) [which require elevated permissions](https://github.com/alfredapp/ignore-in-alfred-workflow/issues/4#issuecomment-1462084194), such as Mac App Store apps.
